---
language: node_js
node_js:
  - "6"

sudo: false

env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

notifications:
  email:
    on_failure: change

cache:
  yarn: true

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn global add phantomjs-prebuilt
  - phantomjs --version
  - yarn global add bower

install:
  - yarn install
  - bower install

script:
  - yarn test
