---
language: node_js
node_js:
  - "5"
  - "4"

sudo: false

notifications:
  email:
    on_failure: change

cache:
  directories:
    - node_modules

before_install:
  - "npm config set spin false"
  - "npm install -g phantomjs-prebuilt"

install:
  - npm install -g bower
  - npm install
  - bower install

script:
  - npm test
