---
language: node_js
node_js:
  - "8"

dist: trusty
sudo: true

services:
  - docker

addons:
  chrome: stable

notifications:
  email:
    on_failure: change

cache:
  yarn: true

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn global add bower
  - docker pull fed03/couchdb:test
  - docker run -d -p 5984:5984 fed03/couchdb:test

install:
  - yarn install --non-interactive
  - bower install

script:
  - yarn test
