---
language: node_js
node_js:
  - "7"

dist: trusty
sudo: false

addons:
  chrome: stable

notifications:
  email:
    on_failure: change

cache:
  yarn: true

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn global add bower

install:
  - yarn install --no-lockfile
  - bower install

script:
  - yarn test
